#!/bin/bash

dirconfpath=/etc/apache2/mods-enabled/dir.conf
read -r -d '' dirconfcontents << EOM
<IfModule mod_dir.c>
    DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm
</IfModule>
EOM
