#!/bin/bash

sudocreatefilewithcontents(){
sudo mv $1 $1.backup;
sudo touch $1;
sudo tee -a $1 >/dev/null <<EOF
$2
EOF
};

createfilewithcontents(){
mv $1 $1.backup;
touch $1;
tee -a $1 >/dev/null <<EOF
$2
EOF
};
