#!/bin/bash

sudo add-apt-repository ppa:certbot/certbot;
sudo apt install python-certbot-apache;
# sudo certbot --apache -d soepaing.com -d www.soepaing.com;
# sudo certbot renew --dry-run;
# IMPORTANT NOTES:
#  Your account credentials have been saved in your Certbot
#   configuration directory at /etc/letsencrypt. You should make a
#   secure backup of this folder now. This configuration directory will
#   also contain certificates and private keys obtained by Certbot so
#   making regular backups of this folder is ideal.
