#!/bin/bash

wpconfpath=/etc/apache2/sites-available/$servername.conf
read -r -d '' wpconfcontents << EOM
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    ServerName $servername
    DocumentRoot /var/www/$servername
    ErrorLog /error.log
    CustomLog /access.log combined
    <Directory /var/www/$servername/>
    AllowOverride All
    </Directory>
RewriteEngine on
</VirtualHost>
EOM
